# Generated by Django 3.1 on 2020-08-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('descriere', models.TextField(blank=True)),
                ('imagine', models.ImageField(blank=True, upload_to='categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('descriere', models.TextField(blank=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagine', models.ImageField(blank=True, upload_to='produs')),
                ('stoc', models.IntegerField()),
                ('disponibil', models.BooleanField(default=True)),
                ('creat', models.DateTimeField(auto_now_add=True)),
                ('updatat', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.categorie')),
            ],
        ),
    ]
