# Generated by Django 3.1 on 2020-08-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ('nume',), 'verbose_name': 'categorie', 'verbose_name_plural': 'categorii'},
        ),
        migrations.AlterModelOptions(
            name='produs',
            options={'ordering': ('nume',), 'verbose_name': 'produs', 'verbose_name_plural': 'produse'},
        ),
    ]
