# Generated by Django 3.1 on 2020-08-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_cos_obiectcos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=250)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total comanda:')),
                ('adresa_email', models.EmailField(blank=True, max_length=250, verbose_name='Adresa de email:')),
                ('creata', models.DateTimeField(auto_now_add=True)),
                ('numeFacturare', models.CharField(blank=True, max_length=250)),
                ('adresaFacturare', models.CharField(blank=True, max_length=250)),
                ('orasFacturare', models.CharField(blank=True, max_length=250)),
                ('codPostalFacturare', models.CharField(blank=True, max_length=250)),
                ('numeLivrare', models.CharField(blank=True, max_length=250)),
                ('adresaLivrare', models.CharField(blank=True, max_length=250)),
                ('orasLivrare', models.CharField(blank=True, max_length=250)),
                ('codPostalLivrare', models.CharField(blank=True, max_length=250)),
                ('taraLivrare', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'Comanda',
                'ordering': ['-creata'],
            },
        ),
        migrations.CreateModel(
            name='ObiectComanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produs', models.CharField(max_length=250)),
                ('cantitate', models.IntegerField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pret:')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.comanda')),
            ],
            options={
                'db_table': 'ObiectComanda',
            },
        ),
    ]
