# Generated by Django 3.1 on 2020-08-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0004_comanda_obiectcomanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='taraFacturare',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
