# Generated by Django 3.1 on 2020-08-20 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazin', '0007_auto_20200817_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='adresaFacturare',
            field=models.CharField(blank=True, max_length=250, verbose_name='Adresa facturare'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='adresaLivrare',
            field=models.CharField(blank=True, max_length=250, verbose_name='Adresa livrare'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='codPostalFacturare',
            field=models.CharField(blank=True, max_length=250, verbose_name='Cod postal facturare'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='codPostalLivrare',
            field=models.CharField(blank=True, max_length=250, verbose_name='Cod postal livrare'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='creata',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data crearii'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='numeFacturare',
            field=models.CharField(blank=True, max_length=250, verbose_name='Nume facturare'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='numeLivrare',
            field=models.CharField(blank=True, max_length=250, verbose_name='Nume livrare'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='orasFacturare',
            field=models.CharField(blank=True, max_length=250, verbose_name='Oras facturare'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='orasLivrare',
            field=models.CharField(blank=True, max_length=250, verbose_name='Oras livrare'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='taraFacturare',
            field=models.CharField(blank=True, max_length=250, verbose_name='Tara facturare'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='taraLivrare',
            field=models.CharField(blank=True, max_length=250, verbose_name='Tara livrare'),
        ),
        migrations.AlterField(
            model_name='produs',
            name='creat',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data crearii'),
        ),
        migrations.AlterField(
            model_name='produs',
            name='disponibil',
            field=models.BooleanField(default=True, verbose_name='Disponibilitate'),
        ),
        migrations.AlterField(
            model_name='produs',
            name='updatat',
            field=models.DateTimeField(auto_now=True, verbose_name='Data actualizarii'),
        ),
        migrations.CreateModel(
            name='Recenzie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj_recenzie', models.CharField(max_length=600)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.produs')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
