# Generated by Django 3.1 on 2020-08-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0008_auto_20200820_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recenzie',
            options={'verbose_name': 'Recenzie', 'verbose_name_plural': 'Recenzii'},
        ),
    ]
